services:
  # ===============================
  # Bancos de dados
  # ===============================
  wallets-db:
    image: postgres:16-alpine
    container_name: lootify-wallets-db
    environment:
      POSTGRES_DB: lootify_wallets_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - wallets_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - lootify-net

  users-db:
    image: postgres:16-alpine
    container_name: lootify-users-db
    environment:
      POSTGRES_DB: lootify_users_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - users_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - lootify-net

  bets-db:
    image: postgres:16-alpine
    container_name: lootify-bets-db
    environment:
      POSTGRES_DB: lootify_bets_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - bets_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - lootify-net

  # ===============================
  # Servi√ßos Elixir
  # ===============================
  users:
    build: ./lootify-users
    container_name: users
    hostname: users.lootify.local
    environment:
      - RELEASE_DISTRIBUTION=name
      - RELEASE_NODE=users@users.lootify.local
      - COOKIE=lootify_cookie
      - DATABASE_URL=ecto://postgres:postgres@postgres/users
    depends_on:
      - postgres
    networks:
      - lootify-net

  wallets:
    build: ./lootify-wallets
    container_name: wallets
    hostname: wallets.lootify.local
    environment:
      - RELEASE_DISTRIBUTION=name
      - RELEASE_NODE=wallets@wallets.lootify.local
      - COOKIE=lootify_cookie
      - DATABASE_URL=ecto://postgres:postgres@postgres/wallets
    depends_on:
      - postgres
    networks:
      - lootify-net

  bets:
    build: ./lootify-bets
    container_name: bets
    hostname: bets.lootify.local
    environment:
      - RELEASE_DISTRIBUTION=name
      - RELEASE_NODE=bets@bets.lootify.local
      - COOKIE=lootify_cookie
      - DATABASE_URL=ecto://postgres:postgres@postgres/bets
    depends_on:
      - postgres
    networks:
      - lootify-net

  gateway:
    build: ./lootify-gateway
    container_name: gateway
    hostname: gateway.lootify.local
    environment:
      - RELEASE_DISTRIBUTION=name
      - RELEASE_NODE=gateway@gateway.lootify.local
      - COOKIE=lootify_cookie
    networks:
      - lootify-net


volumes:
  wallets_data:
  users_data:
  bets_data:

networks:
  lootify-net:
    driver: bridge